feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic
      apiClient:
        url: '${API_URL:https://jsonplaceholder.typicode.com}'
      PacienteClient:
        url: '${API_URL:https://randomuser.me}'

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "health,info"
server:
  port :  9002
  servlet:
    contextPath: /conector